# frontend/Dockerfile.render

FROM node:20-alpine

WORKDIR /app

# Bitno: promenjena putanja jer je kontekst sad root projekta
COPY frontend/package*.json ./
RUN npm install

# Kopiraj ceo frontend folder
COPY frontend/ .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host"]
