# backend/Dockerfile.render

FROM python:3.12-slim

WORKDIR /app

# Kopiraj fajl requirements_render.txt kao requirements.txt u kontejneru
COPY requirements_render.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

EXPOSE 5000

CMD ["python", "app.py"]
